[package]
name = "gotham-demo"
version = "0.1.0"
authors = ["Nicolas Pochet <npochet@gmail.com>"]

[dependencies]
gotham = "0.2"
gotham_derive = "0.2"
hyper = "0.11"
mime = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"